### PR TITLE
Use Python 3 octal syntax

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
#10

**Comment by EvanHahn** [comment]
Does this work in Python 2?

**Comment by r-darwish** [comment]
It works in 2.7. I didn't check 2.6

**Comment by r-darwish** [comment]
I checked 2.6. We're not compatible with it due to various reasons. If 2.6 compatibility is important to you (It mainly means CentOS 6 compatibility) then we should open a different issue for that.

**Comment by EvanHahn** [comment]
Does this break 2.6 where it wasn't broken before?

**Comment by r-darwish** [comment]
No, it was broken before. We use dict comprehension and multiple context manager in a single with statements. Both are not present in Python 2.6

**Comment by EvanHahn** [comment]
Cool; merged. Also made you an admin on the repo—thanks so much for all your help!

**Comment by r-darwish** [comment]
Thanks :)

**Pull request merged**
