### PR TITLE
Channel support

### PR DESCRIPTION
**Pull request by isseu**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Where can I find Channels in the Pushbullet interface?

**Comment by isseu** [comment]
In the website https://www.pushbullet.com/channels.
I dont know where you can see your created channels (maybe because is quite new). I use https://www.pushbullet.com/channel?tag=CHANNELTAG to see my channel and then suscribe.

**Comment by willybarro** [comment]
You can find your created channels here:
https://www.pushbullet.com/my-channels

Or by clicking on your profile picture and going to "My Channels". See

**Comment by willybarro** [comment]
I'm looking forward to this one to be accepted! @isseu My only concern with your PR is that the documentation you've added says that one need to inform the "channel name", but you're using "channel tag" (and I really think that channel tag is the correct way to go, as it is a unique identifier on Pushbullet). Your variables are also named channel_name, even though it's channel_tag. This is inconsistent and may lead to user confusion. Anyway, great PR, that's what I needed :)

**Comment by EvanHahn** [comment]
Looks good to me. @r-darwish, could you take a look at this?

**Comment by r-darwish** [comment]
Seems legit. @isseu - Did you check it on Python 3?

**Comment by isseu** [comment]
@r-darwish yes, working in Python 3.4.2.

**Pull request merged**
